<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Proyecto.Service</RootNamespace>
    <AssemblyName>Proyecto.Service</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proyecto.Repository\Proyecto.Repository.csproj" />
  </ItemGroup>

</Project>
