// <auto-generated />
namespace Proyecto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AgregarCodigos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregarCodigos));
        
        string IMigrationMetadata.Id
        {
            get { return "202608200706029_AgregarCodigos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
